<class>
<keyword>class<keyword>
<identifier>Square<identifier>
<symbol>{<symbol>
<classVarDec>
<keyword>field<keyword>
<keyword>int<keyword>
<identifier>x<identifier>
<identifier>y<identifier>
<symbol>;<symbol>
<classVarDec>
<class>
<keyword>class<keyword>
<identifier>Square<identifier>
<symbol>{<symbol>
<classVarDec>
<keyword>field<keyword>
<keyword>int<keyword>
<identifier>x<identifier>
<identifier>y<identifier>
<symbol>;<symbol>
<classVarDec>
<class>
<keyword>class<keyword>
<identifier>Square<identifier>
<symbol>{<symbol>
<classVarDec>
<keyword>field<keyword>
<keyword>int<keyword>
<identifier>x<identifier>
<identifier>y<identifier>
<symbol>;<symbol>
<classVarDec>
<classVarDec>
<keyword>field<keyword>
<keyword>int<keyword>
<identifier>size<identifier>
<symbol>;<symbol>
<classVarDec>
<subroutineDec>
<keyword>constructor<keyword>
<identifier>Square<identifier>
<identifier>new<identifier>
<class>
<keyword>class<keyword>
<identifier>Square<identifier>
<symbol>{<symbol>
<classVarDec>
<keyword>field<keyword>
<keyword>int<keyword>
<identifier>x<identifier>
<identifier>y<identifier>
<symbol>;<symbol>
<classVarDec>
<classVarDec>
<keyword>field<keyword>
<keyword>int<keyword>
<identifier>size<identifier>
<symbol>;<symbol>
<classVarDec>
<subroutineDec>
<keyword>constructor<keyword>
<identifier>Square<identifier>
<identifier>new<identifier>
<class>
<keyword>class<keyword>
<identifier>Square<identifier>
<symbol>{<symbol>
<classVarDec>
<keyword>field<keyword>
<keyword>int<keyword>
<identifier>x<identifier>
<identifier>y<identifier>
<symbol>;<symbol>
<classVarDec>
<classVarDec>
<keyword>field<keyword>
<keyword>int<keyword>
<identifier>size<identifier>
<symbol>;<symbol>
<classVarDec>
<subroutineDec>
<keyword>constructor<keyword>
<identifier>Square<identifier>
<identifier>new<identifier>
